CREATE DATABASE IF NOT EXISTS CBGRUPOBS
    DEFAULT CHARACTER SET = 'utf8mb4';
USE CBGRUPOBS;

CREATE TABLE USER ( /*Tabla para almacenar la informacion basica del usuario*/
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NUMBER_PHONE INT(12) NOT NULL ,
    NAME VARCHAR(150) NOT NULL,
    CID_RUC VARCHAR(16) NOT NULL
);

CREATE TABLE SERVICE (  /*Tabla para alamcenar los servicios ofrecidos por GrupoBarsa*/
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
    DESCRIPTION VARCHAR(150) NOT NULL,
    IMAGE VARCHAR(150) NOT NULL
);

CREATE TABLE USER_SERVICE ( /*Tabla para registrar si el usuario se interesa por alguno de los servicios ofertados*/
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    SERVICE_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(ID)
);

CREATE TABLE RESERVATION ( /*Tabla que almacena el registro de reservacion del servicio*/
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_SERVICE_ID INT NOT NULL,
    DATE DATE NOT NULL,
    TIME TIME NOT NULL,
    RESERVATION_STATUS INT(1) NOT NULL, /* 0: Cancelado, 1: Pendiente, 2: Confirmado */
    FOREIGN KEY (USER_SERVICE_ID) REFERENCES USER_SERVICE(ID)
)
